'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var injector_8363bc92 = require('rollup-plugin-styles/dist/runtime/inject-css.js');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var injector_8363bc92__default = /*#__PURE__*/_interopDefaultLegacy(injector_8363bc92);

var css = "@keyframes ToggleBar_skeleton__cfaf20cc{0%{background-position:70%}30%{background-position:100%}31%{background-position:0}to{background-position:70%}}.ToggleBar_root__cfaf20cc{--ui-toggle-bar-index:-1;--ui-toggle-bar-inset:0px;--ui-toggle-bar-inset-2:calc(var(--ui-toggle-bar-inset)*2);border:2px solid var(--color-primary-50);border-radius:500px;max-width:100%;min-height:36px;overflow:auto hidden;position:relative}.ToggleBar_root__cfaf20cc:after{animation:ToggleBar_skeleton__cfaf20cc 2s linear infinite reverse;background-attachment:fixed;background-image:linear-gradient(95deg,var(--ui-skeleton-color-base) 0,var(--ui-skeleton-color-base) 45%,var(--ui-skeleton-color-shine) 50%,var(--ui-skeleton-color-base) 55%,var(--ui-skeleton-color-base) 100%);background-repeat:repeat;background-size:500%;border-radius:inherit;content:\"\";display:block;inset:0;opacity:0;pointer-events:none;position:absolute;transition:opacity .3s}.ToggleBar_link__cfaf20cc{align-items:center;border-radius:500px;color:var(--color-primary-50);cursor:pointer;display:flex;flex:1;flex-direction:column;gap:4px;justify-content:center;margin:2px 0;position:relative;text-decoration:none;transition:color .3s;z-index:1}.ToggleBar_link__cfaf20cc:hover{color:var(--color-10)}.ToggleBar_link__cfaf20cc:focus{outline:none}@media (pointer:fine){.ToggleBar_focus__cfaf20cc{background:var(--color-primary-100);border-radius:500px;inset:var(--ui-toggle-bar-inset);left:calc((100% - var(--ui-toggle-bar-inset-2))/var(--ui-toggle-bar-count)*var(--ui-toggle-bar-focus) + var(--ui-toggle-bar-inset));position:absolute;right:calc((100% - var(--ui-toggle-bar-inset-2))/var(--ui-toggle-bar-count)*(var(--ui-toggle-bar-count) - var(--ui-toggle-bar-focus) - 1) + var(--ui-toggle-bar-inset))}}.ToggleBar_active__cfaf20cc,.ToggleBar_active__cfaf20cc:hover{color:var(--color-100)}.ToggleBar_backFocus__cfaf20cc .ToggleBar_focus__cfaf20cc,.ToggleBar_back__cfaf20cc .ToggleBar_selected__cfaf20cc{transition:right .3s .1s,left .3s,opacity .3s}.ToggleBar_forwardFocus__cfaf20cc .ToggleBar_focus__cfaf20cc,.ToggleBar_forward__cfaf20cc .ToggleBar_selected__cfaf20cc{transition:right .3s,left .3s .1s,opacity .3s}.ToggleBar_selected__cfaf20cc{background:var(--color-primary-50);border-radius:500px;inset:var(--ui-toggle-bar-inset);left:calc((100% - var(--ui-toggle-bar-inset-2))/var(--ui-toggle-bar-count)*var(--ui-toggle-bar-index) + var(--ui-toggle-bar-inset));position:absolute;right:calc((100% - var(--ui-toggle-bar-inset-2))/var(--ui-toggle-bar-count)*(var(--ui-toggle-bar-count) - var(--ui-toggle-bar-index) - 1) + var(--ui-toggle-bar-inset))}.ToggleBar_loading__cfaf20cc{cursor:default}.ToggleBar_loading__cfaf20cc:after{opacity:1}";
var modules_2eae4ece = {"root":"ToggleBar_root__cfaf20cc","skeleton":"ToggleBar_skeleton__cfaf20cc","link":"ToggleBar_link__cfaf20cc","focus":"ToggleBar_focus__cfaf20cc","active":"ToggleBar_active__cfaf20cc","backFocus":"ToggleBar_backFocus__cfaf20cc","back":"ToggleBar_back__cfaf20cc","selected":"ToggleBar_selected__cfaf20cc","forwardFocus":"ToggleBar_forwardFocus__cfaf20cc","forward":"ToggleBar_forward__cfaf20cc","loading":"ToggleBar_loading__cfaf20cc"};
injector_8363bc92__default["default"](css,{});

exports.css = css;
exports["default"] = modules_2eae4ece;
