'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var injector_8363bc92 = require('rollup-plugin-styles/dist/runtime/inject-css.js');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var injector_8363bc92__default = /*#__PURE__*/_interopDefaultLegacy(injector_8363bc92);

var css = "@keyframes ToggleBar_skeleton__d64cb4c7{0%{background-position:70%}30%{background-position:100%}31%{background-position:0}to{background-position:70%}}.ToggleBar_root__d64cb4c7{--ui-toggle-bar-index:-1;--ui-toggle-bar-inset:0px;--ui-toggle-bar-inset-2:calc(var(--ui-toggle-bar-inset)*2);border:2px solid var(--color-primary-50);border-radius:500px;max-width:100%;min-height:36px;overflow:auto hidden;position:relative}.ToggleBar_root__d64cb4c7:after{animation:ToggleBar_skeleton__d64cb4c7 2s linear infinite reverse;background-attachment:fixed;background-image:linear-gradient(95deg,var(--ui-skeleton-color-base) 0,var(--ui-skeleton-color-base) 45%,var(--ui-skeleton-color-shine) 50%,var(--ui-skeleton-color-base) 55%,var(--ui-skeleton-color-base) 100%);background-position:70%;background-repeat:repeat;background-size:500%;border-radius:inherit;content:\"\";display:block;inset:0;opacity:0;pointer-events:none;position:absolute;transition:opacity .3s}.ToggleBar_link__d64cb4c7{align-items:center;border-radius:500px;color:var(--color-primary-50);cursor:pointer;display:flex;flex:1;flex-direction:column;gap:4px;justify-content:center;margin:2px 0;position:relative;text-decoration:none;transition:color .3s;z-index:1}.ToggleBar_link__d64cb4c7:hover{color:var(--color-10)}.ToggleBar_link__d64cb4c7:focus{outline:none}@media (pointer:fine){.ToggleBar_focus__d64cb4c7{background:var(--color-primary-100);border-radius:500px;inset:var(--ui-toggle-bar-inset);left:calc((100% - var(--ui-toggle-bar-inset-2))/var(--ui-toggle-bar-count)*var(--ui-toggle-bar-focus) + var(--ui-toggle-bar-inset));position:absolute;right:calc((100% - var(--ui-toggle-bar-inset-2))/var(--ui-toggle-bar-count)*(var(--ui-toggle-bar-count) - var(--ui-toggle-bar-focus) - 1) + var(--ui-toggle-bar-inset))}}.ToggleBar_active__d64cb4c7,.ToggleBar_active__d64cb4c7:hover{color:var(--color-100)}.ToggleBar_backFocus__d64cb4c7 .ToggleBar_focus__d64cb4c7,.ToggleBar_back__d64cb4c7 .ToggleBar_selected__d64cb4c7{transition:right .3s .1s,left .3s,opacity .3s}.ToggleBar_forwardFocus__d64cb4c7 .ToggleBar_focus__d64cb4c7,.ToggleBar_forward__d64cb4c7 .ToggleBar_selected__d64cb4c7{transition:right .3s,left .3s .1s,opacity .3s}.ToggleBar_selected__d64cb4c7{background:var(--color-primary-50);border-radius:500px;inset:var(--ui-toggle-bar-inset);left:calc((100% - var(--ui-toggle-bar-inset-2))/var(--ui-toggle-bar-count)*var(--ui-toggle-bar-index) + var(--ui-toggle-bar-inset));position:absolute;right:calc((100% - var(--ui-toggle-bar-inset-2))/var(--ui-toggle-bar-count)*(var(--ui-toggle-bar-count) - var(--ui-toggle-bar-index) - 1) + var(--ui-toggle-bar-inset))}.ToggleBar_loading__d64cb4c7{cursor:default}.ToggleBar_loading__d64cb4c7:after{opacity:1}";
var modules_2eae4ece = {"root":"ToggleBar_root__d64cb4c7","skeleton":"ToggleBar_skeleton__d64cb4c7","link":"ToggleBar_link__d64cb4c7","focus":"ToggleBar_focus__d64cb4c7","active":"ToggleBar_active__d64cb4c7","backFocus":"ToggleBar_backFocus__d64cb4c7","back":"ToggleBar_back__d64cb4c7","selected":"ToggleBar_selected__d64cb4c7","forwardFocus":"ToggleBar_forwardFocus__d64cb4c7","forward":"ToggleBar_forward__d64cb4c7","loading":"ToggleBar_loading__d64cb4c7"};
injector_8363bc92__default["default"](css,{});

exports.css = css;
exports["default"] = modules_2eae4ece;
